# redmine customize
FROM redmine:latest

#環境変数の自動設定
ENV TZ Asia/Tokyo

# プラグインのコピー
#COPY build/plugins /usr/src/redmine/plugins

# テーマのコピー
#COPY build/themes /usr/src/redmine/public/themes

# configurationファイルのコピー
#COPY build/config/configuration.yml /usr/src/redmine/config/
#COPY build/config/gantt.rb /usr/src/redmine/lib/redmine/helpers/
# macros.rbファイルのコピー
#COPY build/config/macros.rb /usr/src/redmine/lib/redmine/wiki_formatting/macros.rb
