apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: wordpress
  labels:
    app: openshift-lesson
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'wordpress:latest'
  resources: {}
  source:
    git:
      uri: 'https://github.com/asubee/wordpress-openshift'
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'php:latest'
  postCommit: {}
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange

