apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: openshift-lesson
spec:
  accessModes:
    - ReadWriteOnce #単一ノードからRead/Writeが可能。
  resources:
    requests:
      storage: 20Gi

